### ISSUE TITLE
Tree populator chunk problem

### ISSUE THREAD

**Issue by sgdc3** [timvisee/DungeonMaze#37]
![2015-03-28_21 16 04](https://cloud.githubusercontent.com/assets/8779252/6882725/bacfb18c-d58f-11e4-979b-1c85b7b25b11.png)

**Comment by timvisee** [comment]
Hello, 

Thia isn't a bug, these generated things are called 'Oasis', see the OasisPopulator.

Or am I missing something? 

Tim Visée

**Comment by sgdc3** [comment]
Ah ok ;) Can you enhance the borders? It seems like a chunk bug xD

**Comment by timvisee** [comment]
Yes, that would definately be something too look at. The thing is that I currently don't know how to generate and manage structures bigger than a single chunk. I'll take a look at this one that's fixed. This doesn't really have high priority right now.

Tim Visée
