### ISSUE TITLE
Floating torches on surface

### ISSUE THREAD

**Issue by sgdc3** [timvisee/DungeonMaze#43]
![2015-03-28_21 56 08](https://cloud.githubusercontent.com/assets/8779252/6882877/49807254-d595-11e4-816b-95c8db4b6270.png)

**Comment by timvisee** [comment]
Hello,

This is indeed a bug. These torches must be placed by an corrupted 'EntrancePopulator', so that would be something to look at.

Tim Visée

**Comment by timvisee** [comment]
This issue seems to be fixed in the latest Snapshot (0.2).
