### ISSUE TITLE
Add cactus taller than 1 block

### ISSUE THREAD

**Issue by sgdc3** [timvisee/DungeonMaze#44]
![2015-03-28_22 48 22](https://cloud.githubusercontent.com/assets/8779252/6883042/ba1da8fe-d59c-11e4-8c44-16805b81521c.png)

**Comment by timvisee** [comment]
Hello,

Currently this is done because cacti grow taller fairly quickly. Indeed it would be better if the cacti would generate bigger, thus this would be a great enhancement.

Tim Visée

**Comment by Xephi** [comment]
Done ^_^

**Comment by timvisee** [comment]
Brilliant! Thanks for the commit.
