### ISSUE TITLE
Update pom, dependencies and project structure

### ISSUE THREAD

**Issue by sgdc3** [timvisee/DungeonMaze#48]

**Comment by timvisee** [comment]
Sounds like a great idea! It would be awesome if you could also add the (Craft)Bukkit dependencies if that's possible.

**Comment by sgdc3** [comment]
yeah i can do it :)

**Comment by timvisee** [comment]
This seems to be resolved with the latest 0.2 commit.

**Comment by sgdc3** [comment]
Yeah sorry I forgot it! xD

**Comment by timvisee** [comment]
Haha, no problem. That's why I did it, don't worry.
There also seem to be some other issues that are still opened while the issues have been fixed. I'll take a look at those soon.
